object Versions {

    const val compose = "2023.08.00"
    const val navVersion = "2.7.7"
    const val lifecycleVersion = "2.7.0"
    const val coreKtx = "1.12.0"
    const val ktxRuntime = "2.7.0"
    const val composeActivity = "1.8.2"
    const val junit = "4.13.2"
    const val junitExt = "1.1.5"
    const val espresso = "3.5.1"
    const val appCompat = "1.6.1"
    const val material = "1.11.0"
    const val hilt = "2.51"
    const val hiltCompiler = "1.0.0-alpha01"
    const val hiltNavigationCompose = "1.0.0"
    const val multidex = "2.0.1"
    const val retrofit = "2.9.0"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val okhttp = "4.12.0"
    const val coroutines = "1.3.9"
    const val splashScreen = "1.0.0"
    const val coil = "2.6.0"
}